export * as authCtrl from './auth.controller'
export * as userCtrl from './user.controller'
export * as modelCtrl from './model.controller'
export * as pointCtrl from './point.controller'
export * as nativeModelCtrl from './nativeModel.controller'
export * as trackingCtrl from './tracking.controller'
export * as searchCtrl from './search.controller'